[package]
name = "neontest"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "gather"
harness = false

[[bench]]
name = "isnan"
harness = false

[dependencies]
multiversion = "0.8.0"
